modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="dragonblockinfinity"
version="1.0.0"
displayName="Dragon Block Infinity"
description="A Dragon Ball mod for Minecraft Forge 1.20.1"

[[dependencies.dragonblockinfinity]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.dragonblockinfinity]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"
